CREATE TABLE IF NOT EXISTS hits (
	id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
	app VARCHAR(200) NOT NULL,
    uri VARCHAR(200) NOT NULL,
    ip VARCHAR(200) NOT NULL,
    timestamp TIMESTAMP NOT NULL
);






